version: '3.8'

services:
  web:
    build: .
    command: /app/start.sh
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    networks:
      - medexp_network

networks:
  medexp_network:
    driver: bridge