version: '3.8'

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8888
    volumes:
      - /volume1/docker/medexp:/app
    ports:
      - "8888:8888"
    environment:
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=config.settings
    networks:
      - medexp_network

networks:
  medexp_network:
    driver: bridge
