version: '3.8'

services:
  web:
    build: .
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "8888:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      # Portainer will inject the other environment variables here

volumes:
  static_volume: