version: '3.8'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./static:/app/static
      # - /volume1/docker/medexp:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8888:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static
      # - /volume1/docker/medexp:/app
    depends_on:
      - web
    networks:
      - app-network
    command: nginx -g 'daemon off;'


networks:
  app-network:
    driver: bridge