version: '3.8'

services:
  web:
    build: .
    command: gunicorn medexp_app.wsgi:application --bind 0.0.0.0:8888
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "8888:8888"
    networks:
      - medexp_network

networks:
  medexp_network:
    driver: bridge

volumes:
  static_volume: