services:
  backend:
    build: .
    restart: always
    expose:
      - "8000"
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - /var/certbot/conf:/etc/letsencrypt/:ro
    env_file: .env_prod

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - /var/certbot/conf:/etc/letsencrypt:ro
    depends_on:
      - backend

  certbot:
    image: certbot/dns-digitalocean:latest
    volumes:
      - /var/certbot/conf:/etc/letsencrypt/:rw
      - /var/certbot/conf/dns-credentials:/etc/letsencrypt/dns-credentials:ro
    environment:
      - CERTBOT_EMAIL=igonrod@icloud.com
    command: certonly --dns-digitalocean --dns-digitalocean-credentials /etc/letsencrypt/dns-credentials/digitalocean.ini -d vgclinic.com -d *.vgclinic.com --agree-tos -n
    depends_on:
      - nginx